### PR TITLE
Update jose library

### PR DESCRIPTION
**Pull request by fastjames**
Update [jose](https://github.com/potatosalad/erlang-jose) to 1.11.x to remove :crypto calls that were deprecated in OTP23 and were removed in OTP24.

### CODE REVIEW

**Comment by ulissesalmeida** [comment]
@fastjames It seems there's error when booting Goth. Let me know if you need any help to debug it.

**Comment by fastjames** [comment]
> @fastjames It seems there's error when booting Goth. Let me know if you need any help to debug it.

I dug into this a little bit deeper, and there seems to be a knot of dependencies. As of 1.11.4 (the next released version after our current version of 1.10.1), jose specifies an elixir version of `"~> 1.13"` in its mix.exs. So, it looks like jose does not have a release that supports elixir 1.12 / OTP24. :-(

**Comment by ulissesalmeida** [comment]
@fastjames I think they will never add 🤣 

@petermueller What do you think in dropping the Elixir 1.12 support as minor release + jose update?

**Comment by petermueller** [comment]
@ulissesalmeida @fastjames I think it's fine. We should probably update our elixir version in `mix.exs` then as well, if you can do that too, @fastjames 🙏🏻 

Generally, it's enough though that we'd probably want the next release to be `0.3.0` with an upgrade guide.

e.g. 
1. Upgrade your app to Elixir 1.13
2. Update this library
3. Follow the Goth instructions
4. Copy-paste the example from (the README changes from #2) into your app

Either way, I think this update makes sense, even if it's not ideal

Edit: 
I'll make a separate issue for the upgrade guide if you all think a `0.3.0` bump makes sense too

**Comment by fastjames** [comment]
> @ulissesalmeida @fastjames I think it's fine. We should probably update our elixir version in `mix.exs` then as well, if you can do that too, @fastjames 🙏🏻
I have pushed a commit to update the elixir version in mix.exs. Thanks for pointing that out!

**Comment by petermueller** [comment]
I think the errors are to do with however GitHub's repo secrets work

**Comment by ulissesalmeida** [comment]
@petermueller you're right, the secrets are only shared with branches created on this repo. Not on external repos.

**Comment by fastjames** [comment]
> @petermueller you're right, the secrets are only shared with branches created on this repo. Not on external repos.

That's good to know -- I will try to add the needed secrets to my repo.

**Comment by fastjames** [comment]
> > @petermueller you're right, the secrets are only shared with branches created on this repo. Not on external repos.
> 
> That's good to know -- I will try to add the needed secrets to my repo.

I have added secrets for `GCP_CREDENTIALS` and `WAFFLE_BUCKET` to my fork, so maybe that will improve the behavior of the CI suite on my PR.

**Comment by fastjames** [comment]
I opened a PR for the same code on my repo with my secrets configured, and it appears to have run CI successfully. Perhaps one of the maintainers can open a new PR with the equivalent code here and it might pass.

**Comment by ulissesalmeida** [comment]
@fastjames we'll merge it soon with goth upgrade, but before we'll launch a patch.

So no worries! 👍🏽

**Review by petermueller — APPROVED** [review]
confirmed the PR on the fork passes

**Pull request merged**
